WebApplication1/Models/DadosModel.cs
namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class DadosModel : DbContext
    {
        public DadosModel()
            : base("name=DadosModel")
        {
        }

        public virtual DbSet<Transacao> tb_transacao { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Transacao>()
                .Property(e => e.codigoMercadoria)
                .IsUnicode(false);

            modelBuilder.Entity<Transacao>()
                .Property(e => e.tipoMercadoria)
                .IsUnicode(false);

            modelBuilder.Entity<Transacao>()
                .Property(e => e.nomeMercadoria)
                .IsUnicode(false);

            modelBuilder.Entity<Transacao>()
                .Property(e => e.tipoTransacao)
                .IsUnicode(false);
        }
    }
}

WebApplication1/Models/Transacao.cs
namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("vmobi.tb_transacao")]
    public partial class Transacao
    {
        [Key]
        public int ID_TRANSACAO { get; set; }

        [Required]
        [StringLength(5)]
        [Column("ID_MERCADORIA")]
        public string codigoMercadoria { get; set; }

        [Required]
        [StringLength(20)]
        [Column("TP_MERCADORIA")]
        public string tipoMercadoria { get; set; }

        [Required]
        [StringLength(100)]
        [Column("NM_MERCADORIA")]
        public string nomeMercadoria { get; set; }

        [Column("QT_MERCADORIA")]
        public decimal quantidade { get; set; }

        [Column("VL_TRANSACAO")]
        public decimal valorTransacao { get; set; }

        [Required]
        [StringLength(6)]
        [Column("TP_TRANSACAO")]
        public string tipoTransacao { get; set; }
    }
}

WebApplication1/Controllers/CadastroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using MySql.Data.MySqlClient;

namespace Valemobi.Controllers
{
    public class CadastroController : Controller
    {

        public ActionResult PagCadastro()
        {
            return View("Cadastrar");
        }

        public ActionResult CadastrarTransacao(String nome, String codigo, String tipo, String quantidade, String preco, String tipoNegocio)
        {
            DadosModel db = new DadosModel();
            Transacao transacao = new Transacao();
            transacao.nomeMercadoria = nome;
            transacao.codigoMercadoria = codigo;
            transacao.quantidade = Convert.ToInt32(quantidade);
            transacao.tipoMercadoria = tipo;
            transacao.tipoTransacao = tipoNegocio;
            transacao.valorTransacao = Convert.ToInt32(preco);
            try
            {
                db.tb_transacao.Add(transacao);
                db.SaveChanges();
            }
            catch (MySqlException)
            {
                return View("Cadastrar");
            }
            return View("Sucesso");


        }

        public ActionResult ListarTransacoes()
        {
            DadosModel db = new DadosModel();
            db.tb_transacao.ToList();
            return View("Listar", db.tb_transacao.ToList());
        }
       



    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;



namespace Valemobi.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication1/Views/Cadastro/Cadastrar.cshtml
@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar</h2>
<form id="cadMercadoria" action="@Url.Action("CadastrarTransacao","Cadastro")" method="post">

    <div class="form-group row">
        <label class="col-xs-2 col-form-label">Nome da Mercadoria</label>
        <div class="col-xs-10">
            <input class="form-control" type="text" placeholder="Nome Mercadoria" name="nome" required />
        </div>
    </div>

    <div class="form-group row">
        <label class="col-xs-2 col-form-label">Código da Mercadoria</label>
        <div class="col-xs-10">
            <input class="form-control" type="text" placeholder="Código da Mercadoria" name="codigo" maxlength="5" required />
        </div>
    </div>

    <div class="form-group row">
        <label class="col-xs-2 col-form-label">Tipo da Mercadoria</label>
        <div class="col-xs-10">
            <input class="form-control" type="text" placeholder="Tipo da Mercadoria" name="tipo" required />
        </div>
    </div>

    <div class="form-group row">
        <label class="col-xs-2 col-form-label">Quantidade</label>
        <div class="col-xs-10">
            <input class="form-control" type="number" step="1" min="1" placeholder="Quatidade" name="quantidade" required />
        </div>
    </div>

    <div class="form-group row">
        <label class="col-xs-2 col-form-label">Preço (R$)</label>
        <div class="col-xs-10">
            <input class="form-control" type="number" step="1" min="1" placeholder="Preço" name="preco" required />
        </div>
    </div>

    <div class="form-group row">
        <label class="col-xs-2 col-form-label">Tipo do Negócio</label>
        <div class="col-xs-10">
            <select class="form-control" name="tipoNegocio" required>
                <option value="Compra">Compra</option>
                <option value="Venda">Venda</option>
            </select>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Cadastrar</button>

</form>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script>
    $("#cadMercadoria").validate();
</script>

WebApplication1/Views/Cadastro/Listar.cshtml
@model IEnumerable<WebApplication1.Models.Transacao>

@{
    ViewBag.Title = "Listar";
}


<table class="table">
    <tr>
        <th>Código Mercadoria</th>
        <th>Tipo Mercadoria</th>
        <th>Nome Mercadoria</th>
        <th>Quantidade</th>
        <th>Preço</th>
        <th>Tipo do Negócio </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.codigoMercadoria)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tipoMercadoria)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nomeMercadoria)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.quantidade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.valorTransacao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tipoTransacao)
            </td>
        </tr>
    }

</table>

WebApplication1/Views/Cadastro/Sucesso.cshtml
@{
    ViewBag.Title = "Sucesso";
}

<h2>Sucesso</h2>

WebApplication1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}



    <h2 class="display-3">Plataforma de negociação de mercadorias Valemobi</h2>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Valemobi</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>

    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")"><img alt="Brand" src="~/img/logo.png"></a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("PagCadastro", "Cadastro")">Cadastrar Operação</a></li>
                    <li><a href="@Url.Action("ListarTransacoes", "Cadastro")">Lista Operações</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Valemobi @DateTime.Now.Year - João Carvalho - jotecarvalho@gmail.com</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>